Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 8192] # RAM allocated to each VM
    vb.customize ["modifyvm", :id, "--cpus", 8] # CPU allocated to each VM
    vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end

  config.vm.hostname = "y7001.yns.hortonworks.com"
  config.vm.network :private_network, ip: '192.168.70.211'

end
